given = input("Given name:")
last = input("Family name:")
street = input("Street address:")
postal = input("City and postal code:")
print(f"{given} {last}")
print(f"{street}")
print(f"{postal}")